name: IT Bench new benchmark request
description: Request for a new benchmark to be run.
title: "[Registration]: < agent and benchmark name here >"
labels: ["benchmark"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in benchmarking an IT Bench Agent. 
        Please fill out this form to request for a new benchmark to be set up for your agent

        ## Important!

        Before you submit this form, you need to have already registered your agent using the agent registration issue template.

  - type: input
    id: repo_url
    attributes:
      label: "Config Repo"
      description: |
        Provide the GitHub Repository URL where your agent configuration is stored (this is the same repo used in the registration step.)
      placeholder: "e.g. https://github.com/your_org/repo_name"
    validations:
      required: true

  - type: input
    id: benchmark-name
    attributes:
      label: Benchmark Name
      placeholder: my-new-benchmark
    validations:
      required: true
  - type: dropdown
    id: schedule-now
    attributes:
      label: Schedule Now
      description: Do you want this benchmark to be immediately scheduled?
      options:
        - 'true'
        - 'false'
      default: 0
    validations:
      required: true
  
  
      
  - type: markdown
    attributes:
      value: Thank you for completing this form, we will review your request shortly.