name: IT Bench Agent Registration (CISO)
description: Register your CISO ITBench agent for benchmarking
title: "[Registration - CISO]: < agent name here >"
labels: ["registration"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in benchmarking a CISO ITBench Agent.
        Please fill out this form to request connection details for the IT Bench service.

        ## Important!

        Before you submit this form, you need to have completed the following tasks:
        1. Create an empty repository in GitHub with visibility set to private
        2. Install the [ibm-itbench](https://github.com/apps/ibm-itbench-20250310) app into that repository.

        Once those two steps have been completed, please complete this form and provide the URL for the
        repository you created in the relevant section.

  - type: input
    id: agent-name
    attributes:
      label: Agent Name
      placeholder: my-itbench-agent
    validations:
      required: true
  - type: dropdown
    id: agent-type
    attributes:
      label: Agent Type
      description: What type of agent is this?
      options:
        - CISO
      default: 0
    validations:
      required: true
  - type: dropdown
    id: agent-level
    attributes:
      label: Agent Level
      description: What level of agent is this?
      options:
        - Beginner
        - Intermediate
        - Expert
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: scenario-categories
    attributes:
      label: Agent Scenarios
      description: You may select more than one, options not applicable to the agent type will be ignored.
      options:
        - label: resource unavailability
        - label: Kubernetes in Kyverno
        - label: Kubernetes in OPA
        - label: Kubernetes in Kyverno Update
        - label: RHEL9 in OPA
  - type: input
    id: repo_url
    attributes:
      label: "Config Repo"
      description: |
        Provide the GitHub Repository URL that we will create data required for benchmark.
        Please install the [ibm-itbench](https://github.com/apps/ibm-itbench) GitHub App in the repository before submitting this form!.
      placeholder: "e.g. https://github.com/your_org/repo_name"
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: Thank you for completing this form, we will review your request shortly.
